name: ESZTERTAINMENT
favicon: null
layout_spectrum: 0.9798629861325026
typography_spectrum: 0.08411011891439557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.15029256721027195
  lightness: 0.15958687127567828
  saturation: 0.9817555493209511
  rhythmicContrast: 0.5711559364572167
purpose: []
